Replace copyright to AS
autonomoussoftware/metronome-wallet-desktop pull request #288
Opened 2018-05-15 18:42 UTC by ianaya89

Resolves #213

2018-05-15 19:01 UTC, pablen approved these changes

2018-05-15 19:04 UTC, jcvernaleo requested changes
The actual License (not just the copyright statement) needs to be added to `ppa/app/debian/copyright`

2018-05-16 20:57 UTC, gabmontes commented on ppa/app/debian/copyright
> +Copyright 2018 Autonomous Software. <labs@autonomous.sh>
Not sure about this email address...

2018-05-17 14:53 UTC, gabmontes approved these changes

2018-05-17 14:57 UTC, jcvernaleo approved these changes

2018-05-17 14:59 UTC, merged