Add sentry support
autonomoussoftware/metronome-wallet-desktop pull request #96
Opened 2018-02-20 18:18 UTC by ianaya89

Resolves #50

2018-02-20 19:59 UTC, gabmontes commented on public/electron.js
> +  logger.info('App ready, initializing 🚀')
Nice rocket but prefer plain text in logs. Don't want to shut remote loggers down with Unicode chars. Please remove it.

2018-02-20 19:59 UTC, gabmontes commented on src/index.js
> +    'https://d99caae5ca1b495584e5aa3187966f30@sentry.io/277183'
This should be taken from `config.SENTRY_DSN`.

2018-02-20 19:59 UTC, gabmontes commented
@ianaya89 did you cancel this PR?

2018-02-21 13:14 UTC, eafelix approved these changes
💯

2018-02-21 13:15 UTC, eafelix requested changes

2018-02-21 13:15 UTC, eafelix commented on public/electron.js
> +  logger.info('App ready, initializing 🚀')
where could it represent a problem?

2018-02-21 17:43 UTC, eafelix approved these changes

2018-02-21 18:04 UTC, gabmontes approved these changes

2018-02-21 18:04 UTC, merged